name: Deafult

on:
  pull_request:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/ci-main.yml
    with:
      use-coverage: false
      final-commands: |
        make lint

  lint-docstrings:
    name: Lint Docstrings
    uses: ./.github/workflows/ci-main.yml
    with:
      use-coverage: false
      final-commands: |
        make lint-docstrings

  check:
    name: Check
    uses: ./.github/workflows/ci-main.yml
    with:
      use-coverage: false
      final-commands: |
        make check-all
